#?? ????? ?? ??
file:
  directory: D:\LHC\download\quadruaple

#???? ?? ???
const:
  default-review-size: 10

#?????? ??
spring:
  profiles:
    active: secret
  application:
    name: quadruaple
  datasource:
    #    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    #    url: jdbc:log4jdbc:mariadb://localhost/p2
    #    username: root
    #    password: green502
    config:
      import: "classpath:application-secret.yml"
      activate:
        on-profile: secret #prod ???? ??? ??
  #File ??? ??
  servlet:
    multipart:
      max-file-size: 50MB

jwt:
  issuer: green@green.kr
  secret-key: secretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKey


#MyBatis ??
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml
#  type-aliases-package: com/green/project_quadruaple

#Swagger ??
springdoc:
  swagger-ui:
    default-models-expand-depth: 10
    display-request-duration: true
    groups-order: asc
    operations-sorter: method
    path: /swagger
    tags-sorter: alpha
  cache:
    disabled: true