file:
  directory:/home/download/quadruaple

constant:
  jwt-const:
    access-token-expiry: 180 #3분 (MS)

#spring:
    #  datasource:
    #url: jdbc:log4jdbc:mariadb://localhost/quadruaple
    #username: even_second_1
    #password: coating


spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy # 기본 MariaDB 드라이버 사용
    url: jdbc:log4jdbc:mariadb://192.168.0.144/db_even_second_1 # log4jdbc 제거
    username: even_second_1
    password: coating